source 'https://rubygems.org'

gem 'nanoc'                  , '~> 3.7.3'
gem 'nanoc-sprockets'        , '~> 0.0.2'
gem 'sprockets-sass'         , '~> 1.0.3'
gem 'uglifier'               , '~> 2.5.0'
gem 'therubyracer'           , '~> 0.12.0'
gem 'sass'                   , '~> 3.4.2'

group :development do
  gem 'guard-nanoc'          , '~> 1.0.1'
end
